openapi: 3.2.0
info:
  title: Loadsmart Shipment Stops API
  x-logo:
    altText: Loadsmart API
    url: https://developer.loadsmart.com/logo.svg
  description: Loadsmart API provides endpoints to quote, book and track shipments autonomously.
  version: 1.0.0
servers:
- url: https://api.loadsmart.com
  description: Production server
- url: https://api.sandbox.loadsmart.com
  description: Sandbox environment
tags:
- name: Shipment Stops
  description: Stops of a shipment
paths:
  /api/v2/shipments/{shipment_id}/stops/{stop_id}/confirm_appointment:
    put:
      summary: Confirm stop appointment
      tags:
      - Shipment Stops
      description: Confirm the time and date of the appointment for the stop
      security:
      - Application-JWT:
        - shipment_write
      parameters:
      - in: path
        name: shipment_id
        required: true
        schema:
          description: Shipment UUID
          type: string
          format: uuid
      - in: path
        name: stop_id
        required: true
        schema:
          description: Stop UUID
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                confirmed:
                  description: If it is confirmed
                  type: boolean
                window_start:
                  description: A datetime that represents the start of a time window for this appointment. In UTC time.
                  type: string
                  format: date-time
                window_end:
                  description: A datetime that represents the end of a time window for this appointment. In UTC time.
                  type: string
                  format: date-time
                scheduler_appt_id:
                  description: An ID that represents this appointment.
                  type: string
                  format: uuid
                confirmation_number:
                  description: A number that identifies this appointment.
                  type: string
                contact_name:
                  description: The contact name responsible for this appointment.
                  type: string
            example:
              confirmed: true
              window_start: 2020-02-14 08:00:00+00:00
              window_end: 2020-02-14 09:00:00+00:00
              scheduler_appt_id: 029a8462-a04e-4ad8-80d8-e6978db2fb55
              confirmation_number: 123456789
              contact_name: Joe Smith
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      confirmed:
                        description: If it is confirmed
                        type: boolean
                      window_start:
                        description: A datetime that represents the start of a time window for this appointment. In UTC time.
                        type: string
                        format: date-time
                      window_end:
                        description: A datetime that represents the end of a time window for this appointment. In UTC time.
                        type: string
                        format: date-time
                      scheduler_appt_id:
                        description: An ID that represents this appointment.
                        type: string
                        format: uuid
                      confirmation_number:
                        description: A number that identifies this appointment.
                        type: string
                      contact_name:
                        description: The contact name responsible for this appointment.
                        type: string
              example:
                confirmed: true
                window_start: 2020-02-14 08:00:00+00:00
                window_end: 2020-02-14 09:00:00+00:00
                scheduler_appt_id: 029a8462-a04e-4ad8-80d8-e6978db2fb55
                confirmation_number: 123456789
                contact_name: Joe Smith
        '404':
          description: Shipment or stop not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                    - invalid_data
                  error_description:
                    type: string
                    description: Description of what happened
                  errors:
                    type: object
                    description: Object where each field is a key and the value is an array of errors
                required:
                - error
                - error_description
              example:
                error: object_not_found
                error_description: Object not found
        '422':
          description: Payload is invalid and the confirmation can't be made
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                    - invalid_data
                  error_description:
                    type: string
                    description: Description of what happened
                  errors:
                    type: object
                    description: Object where each field is a key and the value is an array of errors
                required:
                - error
                - error_description
              example:
                error: invalid_data
                error_description: Can't create the object
                errors:
                  field_name:
                  - This field is required.
                  other_field:
                  - Expected string but received integer.
      operationId: putApiV2ShipmentsByShipmentIdStopsByStopIdConfirmAppointment
      x-operation-id-source: derived
components:
  securitySchemes:
    Application-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorize the request with the application context (preferred\nfor the endpoints that support it):\n\n```\n{\n  \"sub\": \"sys\",\n  \"iss\": \"token-issuer\",\n  \"exp\": 1626239022,\n  \"iat\": 1517239022\n}\n```\n"
    User-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorize the request with an user context. A payload example\nwould be:\n\n```\n{\n  \"sub\": \"usr:87127882-d1db-4e50-8f7c-c792a80d7c49\",\n  \"iss\": \"token-issuer\",\n  \"iat\": 1517239022,\n  \"exp\": 1626239022\n}\n```\n"
