openapi: 3.2.0
info:
  title: Loadsmart Capacity API
  x-logo:
    altText: Loadsmart API
    url: https://developer.loadsmart.com/logo.svg
  description: Loadsmart API provides endpoints to quote, book and track shipments autonomously.
  version: 1.0.0
servers:
- url: https://api.loadsmart.com
  description: Production server
- url: https://api.sandbox.loadsmart.com
  description: Sandbox environment
tags:
- name: Capacity
  description: 'Manages new capacity. A capacity is a truck that is

    empty and it''s location.'
paths:
  /api/v2/capacity:
    post:
      summary: Create capacity
      description: 'Inform us about a list of available trucks.


        The available trucks must have at least a point of pickup, the

        delivery is not mandatory but will increase the chances of best

        matching for our loads.


        The capacity represents an empty truck position. For different

        empty positions for the same truck, the available trucks and

        their ids must be different. We suggest that you use an uuid to

        represent the `ref_number` attribute on your side, because this

        identifier will be reused across other endpoints.'
      tags:
      - Capacity
      security:
      - User-JWT:
        - capacity_write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
              - type: array
                title: capacity:spot
                items:
                  type: object
                  required:
                  - carrier_identification
                  - ref_number
                  - equipment_type
                  - available_at
                  - pickup
                  properties:
                    available_at:
                      type: string
                      description: The date and time the truck is going to be available. You must not provide timezone info.
                      format: date-time
                      pattern: YYYY-MM-DDThh:mm:ss
                    delivery_deadhead:
                      type: number
                      description: The distance between the truck and the delivery
                    pickup_deadhead:
                      type: number
                      description: The distance between the truck and the pickup
                    expires_at:
                      type: string
                      format: date-time
                    carrier_identification:
                      description: 'An identifier for the carrier.

                        There are two ways to identify a carrier, by Loadsmart Carrier ID or by MC+DOT combination.

                        If you provide carrier ID, you must not provide any information for MC and DOT.

                        If you provide MC and DOT, you must not provide carrier ID information.

                        '
                      oneOf:
                      - title: Carrier identified by Carrier ID
                        type: object
                        properties:
                          carrier_id:
                            type: string
                            format: uuid
                            description: Carrier UUID (provided by Loadsmart)
                          mc:
                            type: string
                            description: Carrier MC Number (Motor Carrier Number)
                          dot:
                            type: string
                            description: Carrier DOT Number
                        required:
                        - carrier_id
                      - title: Carrier identified by MC and DOT
                        type: object
                        properties:
                          carrier_id:
                            type: string
                            format: uuid
                            description: Carrier UUID (provided by Loadsmart)
                          mc:
                            type: string
                            description: Carrier MC Number (Motor Carrier Number)
                          dot:
                            type: string
                            description: Carrier DOT Number
                        required:
                        - mc
                        - dot
                    ref_number:
                      type: string
                      description: 'Unique id for the given capacity, this must represent the id for this capacity on your side.

                        This represents the empty truck location identifier. You must use different ids for different

                        empty locations or dates, even if its the same capacity/truck.


                        We suggest that you use an uuid to create this identifier.

                        '
                    fleet_id:
                      type: string
                      description: Fleet identifier for this capacity.
                    equipment_type:
                      type: string
                      enum:
                      - DRV
                      - FBE
                      - RFR
                      - CON
                      - CUR
                      - DDP
                      - IMC
                      - SDK
                      - STK
                      description: 'Truck''s type. Must be one of the following:

                        `DRV` for Dry Van

                        `FBE` for Flatbed

                        `RFR` for Reefer

                        `CON` for Conestoga

                        `CUR` for Curtainside

                        `DDP` for Double Drop

                        `IMC` for Intermodal

                        `SDK` for Step Deck

                        `STK` for Straight Truck

                        '
                    rate:
                      type: number
                      description: The all in rate for the lane.
                    rate_per_mile:
                      type: number
                      description: Indicates the value per miles
                    is_backhaul:
                      type: boolean
                      description: Indicates whether the capacity is backhaul or not.
                    contacts:
                      type: array
                      description: A list of who should be contacted by us for this capacity.
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          phone_number:
                            type: string
                            pattern: \+\d{4,15}
                            maxLength: 16
                            description: Phone number following the format [E.164](https://www.itu.int/rec/T-REC-E.164/)
                          email:
                            type: string
                    pickup:
                      description: 'The desired location for pickup.

                        Certain parameters are required for this request.

                        You must include either zipcode, state or coords.

                        If you provide coords, you must not provide any other address information.

                        If you include a City, then a State should also be provided to avoid

                        ambiguous information.

                        Missing geographical data will be automatically filled by the API.

                        '
                      oneOf:
                      - title: Place with State
                        type: object
                        properties:
                          city:
                            type: string
                            description: Name of city
                          state:
                            type: string
                            description: Two letter state or equivalent administrative boundary
                          zipcode:
                            type: string
                            description: zipcode (first five digits)
                          country:
                            type: string
                            pattern: ^[A-Z]{3}$
                            description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                              If no country is provided, ''USA'' is inferred.

                              '
                          coords:
                            type: object
                            required:
                            - latitude
                            - longitude
                            properties:
                              latitude:
                                type: number
                                description: Approximate latitude for the place
                              longitude:
                                type: number
                                description: Approximate longitude for the place
                        required:
                        - state
                      - title: Place with Zipcode
                        type: object
                        properties:
                          city:
                            type: string
                            description: Name of city
                          state:
                            type: string
                            description: Two letter state or equivalent administrative boundary
                          zipcode:
                            type: string
                            description: zipcode (first five digits)
                          country:
                            type: string
                            pattern: ^[A-Z]{3}$
                            description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                              If no country is provided, ''USA'' is inferred.

                              '
                          coords:
                            type: object
                            required:
                            - latitude
                            - longitude
                            properties:
                              latitude:
                                type: number
                                description: Approximate latitude for the place
                              longitude:
                                type: number
                                description: Approximate longitude for the place
                        required:
                        - zipcode
                      - title: Place with City must have State
                        type: object
                        properties:
                          city:
                            type: string
                            description: Name of city
                          state:
                            type: string
                            description: Two letter state or equivalent administrative boundary
                          zipcode:
                            type: string
                            description: zipcode (first five digits)
                          country:
                            type: string
                            pattern: ^[A-Z]{3}$
                            description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                              If no country is provided, ''USA'' is inferred.

                              '
                          coords:
                            type: object
                            required:
                            - latitude
                            - longitude
                            properties:
                              latitude:
                                type: number
                                description: Approximate latitude for the place
                              longitude:
                                type: number
                                description: Approximate longitude for the place
                        required:
                        - city
                        - state
                      - title: Place with Coords
                        type: object
                        properties:
                          city:
                            type: string
                            description: Name of city
                          state:
                            type: string
                            description: Two letter state or equivalent administrative boundary
                          zipcode:
                            type: string
                            description: zipcode (first five digits)
                          country:
                            type: string
                            pattern: ^[A-Z]{3}$
                            description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                              If no country is provided, ''USA'' is inferred.

                              '
                          coords:
                            type: object
                            required:
                            - latitude
                            - longitude
                            properties:
                              latitude:
                                type: number
                                description: Approximate latitude for the place
                              longitude:
                                type: number
                                description: Approximate longitude for the place
                        required:
                        - coords
                    delivery:
                      type: array
                      description: 'The desired location for delivery.

                        Certain parameters are required for this request.

                        You must include either zipcode, state or coords.

                        If you provide coords, you must not provide any other address information.

                        If you include a City, then a State should also be provided to avoid

                        ambiguous information.

                        Missing geographical data will be automatically filled by the API.

                        '
                      items:
                        oneOf:
                        - title: Place with State
                          type: object
                          properties:
                            city:
                              type: string
                              description: Name of city
                            state:
                              type: string
                              description: Two letter state or equivalent administrative boundary
                            zipcode:
                              type: string
                              description: zipcode (first five digits)
                            country:
                              type: string
                              pattern: ^[A-Z]{3}$
                              description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                                If no country is provided, ''USA'' is inferred.

                                '
                            coords:
                              type: object
                              required:
                              - latitude
                              - longitude
                              properties:
                                latitude:
                                  type: number
                                  description: Approximate latitude for the place
                                longitude:
                                  type: number
                                  description: Approximate longitude for the place
                          required:
                          - state
                        - title: Place with Zipcode
                          type: object
                          properties:
                            city:
                              type: string
                              description: Name of city
                            state:
                              type: string
                              description: Two letter state or equivalent administrative boundary
                            zipcode:
                              type: string
                              description: zipcode (first five digits)
                            country:
                              type: string
                              pattern: ^[A-Z]{3}$
                              description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                                If no country is provided, ''USA'' is inferred.

                                '
                            coords:
                              type: object
                              required:
                              - latitude
                              - longitude
                              properties:
                                latitude:
                                  type: number
                                  description: Approximate latitude for the place
                                longitude:
                                  type: number
                                  description: Approximate longitude for the place
                          required:
                          - zipcode
                        - title: Place with City must have State
                          type: object
                          properties:
                            city:
                              type: string
                              description: Name of city
                            state:
                              type: string
                              description: Two letter state or equivalent administrative boundary
                            zipcode:
                              type: string
                              description: zipcode (first five digits)
                            country:
                              type: string
                              pattern: ^[A-Z]{3}$
                              description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                                If no country is provided, ''USA'' is inferred.

                                '
                            coords:
                              type: object
                              required:
                              - latitude
                              - longitude
                              properties:
                                latitude:
                                  type: number
                                  description: Approximate latitude for the place
                                longitude:
                                  type: number
                                  description: Approximate longitude for the place
                          required:
                          - city
                          - state
                        - title: Place with Coords
                          type: object
                          properties:
                            city:
                              type: string
                              description: Name of city
                            state:
                              type: string
                              description: Two letter state or equivalent administrative boundary
                            zipcode:
                              type: string
                              description: zipcode (first five digits)
                            country:
                              type: string
                              pattern: ^[A-Z]{3}$
                              description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                                If no country is provided, ''USA'' is inferred.

                                '
                            coords:
                              type: object
                              required:
                              - latitude
                              - longitude
                              properties:
                                latitude:
                                  type: number
                                  description: Approximate latitude for the place
                                longitude:
                                  type: number
                                  description: Approximate longitude for the place
                          required:
                          - coords
              - type: array
                title: capacity:static
                items:
                  type: object
                  required:
                  - carrier_identification
                  - ref_number
                  - equipment_type
                  - available_dow
                  - pickup
                  - contacts
                  properties:
                    available_dow:
                      type: array
                      description: A list of the capacity's available days of week.
                      items:
                        type: string
                        enum:
                        - Mon
                        - Tue
                        - Wed
                        - Thu
                        - Fri
                        - Sat
                        - Sun
                    carrier_identification:
                      description: 'An identifier for the carrier.

                        There are two ways to identify a carrier, by Loadsmart Carrier ID or by MC+DOT combination.

                        If you provide carrier ID, you must not provide any information for MC and DOT.

                        If you provide MC and DOT, you must not provide carrier ID information.

                        '
                      oneOf:
                      - title: Carrier identified by Carrier ID
                        type: object
                        properties:
                          carrier_id:
                            type: string
                            format: uuid
                            description: Carrier UUID (provided by Loadsmart)
                          mc:
                            type: string
                            description: Carrier MC Number (Motor Carrier Number)
                          dot:
                            type: string
                            description: Carrier DOT Number
                        required:
                        - carrier_id
                      - title: Carrier identified by MC and DOT
                        type: object
                        properties:
                          carrier_id:
                            type: string
                            format: uuid
                            description: Carrier UUID (provided by Loadsmart)
                          mc:
                            type: string
                            description: Carrier MC Number (Motor Carrier Number)
                          dot:
                            type: string
                            description: Carrier DOT Number
                        required:
                        - mc
                        - dot
                    ref_number:
                      type: string
                      description: 'Unique id for the given capacity, this must represent the id for this capacity on your side.

                        This represents the empty truck location identifier. You must use different ids for different

                        empty locations or dates, even if its the same capacity/truck.


                        We suggest that you use an uuid to create this identifier.

                        '
                    fleet_id:
                      type: string
                      description: Fleet identifier for this capacity.
                    equipment_type:
                      type: string
                      enum:
                      - DRV
                      - FBE
                      - RFR
                      - CON
                      - CUR
                      - DDP
                      - IMC
                      - SDK
                      - STK
                      description: 'Truck''s type. Must be one of the following:

                        `DRV` for Dry Van

                        `FBE` for Flatbed

                        `RFR` for Reefer

                        `CON` for Conestoga

                        `CUR` for Curtainside

                        `DDP` for Double Drop

                        `IMC` for Intermodal

                        `SDK` for Step Deck

                        `STK` for Straight Truck

                        '
                    rate:
                      type: number
                      description: The all in rate for the lane.
                    rate_per_mile:
                      type: number
                      description: Indicates the value per miles
                    is_backhaul:
                      type: boolean
                      description: Indicates whether the capacity is backhaul or not.
                    contacts:
                      type: array
                      description: A list of who should be contacted by us for this capacity.
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          phone_number:
                            type: string
                            pattern: \+\d{4,15}
                            maxLength: 16
                            description: Phone number following the format [E.164](https://www.itu.int/rec/T-REC-E.164/)
                          email:
                            type: string
                    pickup:
                      description: 'The desired location for pickup.

                        Certain parameters are required for this request.

                        You must include either zipcode, state or coords.

                        If you provide coords, you must not provide any other address information.

                        If you include a City, then a State should also be provided to avoid

                        ambiguous information.

                        Missing geographical data will be automatically filled by the API.

                        '
                      oneOf:
                      - title: Place with State
                        type: object
                        properties:
                          city:
                            type: string
                            description: Name of city
                          state:
                            type: string
                            description: Two letter state or equivalent administrative boundary
                          zipcode:
                            type: string
                            description: zipcode (first five digits)
                          country:
                            type: string
                            pattern: ^[A-Z]{3}$
                            description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                              If no country is provided, ''USA'' is inferred.

                              '
                          coords:
                            type: object
                            required:
                            - latitude
                            - longitude
                            properties:
                              latitude:
                                type: number
                                description: Approximate latitude for the place
                              longitude:
                                type: number
                                description: Approximate longitude for the place
                        required:
                        - state
                      - title: Place with Zipcode
                        type: object
                        properties:
                          city:
                            type: string
                            description: Name of city
                          state:
                            type: string
                            description: Two letter state or equivalent administrative boundary
                          zipcode:
                            type: string
                            description: zipcode (first five digits)
                          country:
                            type: string
                            pattern: ^[A-Z]{3}$
                            description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                              If no country is provided, ''USA'' is inferred.

                              '
                          coords:
                            type: object
                            required:
                            - latitude
                            - longitude
                            properties:
                              latitude:
                                type: number
                                description: Approximate latitude for the place
                              longitude:
                                type: number
                                description: Approximate longitude for the place
                        required:
                        - zipcode
                      - title: Place with City must have State
                        type: object
                        properties:
                          city:
                            type: string
                            description: Name of city
                          state:
                            type: string
                            description: Two letter state or equivalent administrative boundary
                          zipcode:
                            type: string
                            description: zipcode (first five digits)
                          country:
                            type: string
                            pattern: ^[A-Z]{3}$
                            description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                              If no country is provided, ''USA'' is inferred.

                              '
                          coords:
                            type: object
                            required:
                            - latitude
                            - longitude
                            properties:
                              latitude:
                                type: number
                                description: Approximate latitude for the place
                              longitude:
                                type: number
                                description: Approximate longitude for the place
                        required:
                        - city
                        - state
                      - title: Place with Coords
                        type: object
                        properties:
                          city:
                            type: string
                            description: Name of city
                          state:
                            type: string
                            description: Two letter state or equivalent administrative boundary
                          zipcode:
                            type: string
                            description: zipcode (first five digits)
                          country:
                            type: string
                            pattern: ^[A-Z]{3}$
                            description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                              If no country is provided, ''USA'' is inferred.

                              '
                          coords:
                            type: object
                            required:
                            - latitude
                            - longitude
                            properties:
                              latitude:
                                type: number
                                description: Approximate latitude for the place
                              longitude:
                                type: number
                                description: Approximate longitude for the place
                        required:
                        - coords
                    delivery:
                      type: array
                      description: 'The desired location for delivery.

                        Certain parameters are required for this request.

                        You must include either zipcode, state or coords.

                        If you provide coords, you must not provide any other address information.

                        If you include a City, then a State should also be provided to avoid

                        ambiguous information.

                        Missing geographical data will be automatically filled by the API.

                        '
                      items:
                        oneOf:
                        - title: Place with State
                          type: object
                          properties:
                            city:
                              type: string
                              description: Name of city
                            state:
                              type: string
                              description: Two letter state or equivalent administrative boundary
                            zipcode:
                              type: string
                              description: zipcode (first five digits)
                            country:
                              type: string
                              pattern: ^[A-Z]{3}$
                              description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                                If no country is provided, ''USA'' is inferred.

                                '
                            coords:
                              type: object
                              required:
                              - latitude
                              - longitude
                              properties:
                                latitude:
                                  type: number
                                  description: Approximate latitude for the place
                                longitude:
                                  type: number
                                  description: Approximate longitude for the place
                          required:
                          - state
                        - title: Place with Zipcode
                          type: object
                          properties:
                            city:
                              type: string
                              description: Name of city
                            state:
                              type: string
                              description: Two letter state or equivalent administrative boundary
                            zipcode:
                              type: string
                              description: zipcode (first five digits)
                            country:
                              type: string
                              pattern: ^[A-Z]{3}$
                              description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                                If no country is provided, ''USA'' is inferred.

                                '
                            coords:
                              type: object
                              required:
                              - latitude
                              - longitude
                              properties:
                                latitude:
                                  type: number
                                  description: Approximate latitude for the place
                                longitude:
                                  type: number
                                  description: Approximate longitude for the place
                          required:
                          - zipcode
                        - title: Place with City must have State
                          type: object
                          properties:
                            city:
                              type: string
                              description: Name of city
                            state:
                              type: string
                              description: Two letter state or equivalent administrative boundary
                            zipcode:
                              type: string
                              description: zipcode (first five digits)
                            country:
                              type: string
                              pattern: ^[A-Z]{3}$
                              description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                                If no country is provided, ''USA'' is inferred.

                                '
                            coords:
                              type: object
                              required:
                              - latitude
                              - longitude
                              properties:
                                latitude:
                                  type: number
                                  description: Approximate latitude for the place
                                longitude:
                                  type: number
                                  description: Approximate longitude for the place
                          required:
                          - city
                          - state
                        - title: Place with Coords
                          type: object
                          properties:
                            city:
                              type: string
                              description: Name of city
                            state:
                              type: string
                              description: Two letter state or equivalent administrative boundary
                            zipcode:
                              type: string
                              description: zipcode (first five digits)
                            country:
                              type: string
                              pattern: ^[A-Z]{3}$
                              description: '3-letter country code, uppercase (ISO 3166-1 alpha-3)

                                If no country is provided, ''USA'' is inferred.

                                '
                            coords:
                              type: object
                              required:
                              - latitude
                              - longitude
                              properties:
                                latitude:
                                  type: number
                                  description: Approximate latitude for the place
                                longitude:
                                  type: number
                                  description: Approximate longitude for the place
                          required:
                          - coords
            examples:
              Spot Capacity:
                value:
                - available_at: 2018-11-22 10:00:00
                  carrier_id: 9f87d040-f843-42e7-887a-45bea55e76f3
                  ref_number: c6786277-e20e-4e0e-b28b-972d7bac365b
                  fleet_id: XYZ123
                  equipment_type: DRV
                  rate: 1200
                  is_backhaul: false
                  contacts:
                  - name: Foo Bar
                    phone_number: 1111111111
                  pickup:
                    city: New York
                    state: NY
                    zipcode: '10013'
                    country: USA
                  delivery:
                    city: Nashville
                    state: TN
                    zipcode: '37011'
                    country: USA
              Static Capacity:
                value:
                - available_dow:
                  - Mon
                  - Sun
                  carrier_id: 9f87d040-f843-42e7-887a-45bea55e76f3
                  ref_number: c6786277-e20e-4e0e-b28b-972d7bac365b
                  fleet_id: XYZ123
                  equipment_type: DRV
                  rate: 1200
                  is_backhaul: false
                  contacts:
                  - name: Foo Bar
                    phone_number: 1111111111
                  pickup:
                    city: New York
                    state: NY
                    zipcode: '10013'
                    country: USA
                  delivery:
                    city: Nashville
                    state: TN
                    zipcode: '37011'
                    country: USA
              Capacity with coords:
                value:
                - available_at: 2018-11-22 10:00:00
                  carrier_id: 9f87d040-f843-42e7-887a-45bea55e76f3
                  ref_number: c6786277-e20e-4e0e-b28b-972d7bac365b
                  fleet_id: XYZ123
                  equipment_type: DRV
                  rate: 1200
                  is_backhaul: false
                  contacts:
                  - name: Foo Bar
                    phone_number: 1111111111
                  pickup:
                    coords:
                      latitude: 40.7128
                      longitude: -74.006
                  delivery:
                    city: Nashville
                    state: TN
                    zipcode: '37011'
                    country: USA
      responses:
        '202':
          description: All provided data is valid and the available trucks are being created
        '422':
          description: Payload is invalid and a capacity can't be created
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                    - invalid_data
                  error_description:
                    type: string
                    description: Description of what happened
                  errors:
                    type: object
                    description: Object where each field is a key and the value is an array of errors
                required:
                - error
                - error_description
              example:
                error: invalid_data
                error_description: Can't create the object
                errors:
                  field_name:
                  - This field is required.
                  other_field:
                  - Expected string but received integer.
      operationId: postApiV2Capacity
      x-operation-id-source: derived
  /api/v2/capacity/{capacity_ref_number}:
    delete:
      summary: Delete a Capacity
      tags:
      - Capacity
      security:
      - User-JWT:
        - capacity_write
      parameters:
      - in: path
        name: ref_number
        required: true
        schema:
          type: string
          description: 'Unique id for the given capacity, this must represent the id for this capacity on your side.

            This represents the empty truck location identifier. You must use different ids for different

            empty locations or dates, even if its the same capacity/truck.


            We suggest that you use an uuid to create this identifier.

            '
      responses:
        '204':
          description: Capacity deleted
        '404':
          description: Capacity not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                    - invalid_data
                  error_description:
                    type: string
                    description: Description of what happened
                  errors:
                    type: object
                    description: Object where each field is a key and the value is an array of errors
                required:
                - error
                - error_description
              example:
                error: object_not_found
                error_description: Object not found
      operationId: deleteApiV2CapacityByCapacityRefNumber
      x-operation-id-source: derived
components:
  securitySchemes:
    Application-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorize the request with the application context (preferred\nfor the endpoints that support it):\n\n```\n{\n  \"sub\": \"sys\",\n  \"iss\": \"token-issuer\",\n  \"exp\": 1626239022,\n  \"iat\": 1517239022\n}\n```\n"
    User-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorize the request with an user context. A payload example\nwould be:\n\n```\n{\n  \"sub\": \"usr:87127882-d1db-4e50-8f7c-c792a80d7c49\",\n  \"iss\": \"token-issuer\",\n  \"iat\": 1517239022,\n  \"exp\": 1626239022\n}\n```\n"
