openapi: 3.2.0
info:
  title: Loadsmart Shippers API
  x-logo:
    altText: Loadsmart API
    url: https://developer.loadsmart.com/logo.svg
  description: Loadsmart API provides endpoints to quote, book and track shipments autonomously.
  version: 1.0.0
servers:
- url: https://api.loadsmart.com
  description: Production server
- url: https://api.sandbox.loadsmart.com
  description: Sandbox environment
tags:
- name: Shippers
  description: 'Manage shippers. A shipper is a company that creates and manages

    loads on Loadsmart platform.'
paths:
  /api/v2/shippers:
    post:
      summary: Create shipper
      tags:
      - Shippers
      security:
      - Application-JWT:
        - shipper_write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: Unique identifier for this shipper
                  readOnly: true
                company_name:
                  type: string
                  description: Company name
                  minLength: 10
                  maxLength: 255
                account:
                  type: object
                  writeOnly: true
                  properties:
                    email:
                      type: string
                      format: email
                      description: User's email address
                      maxLength: 100
                    first_name:
                      type: string
                      description: User's first name
                      maxLength: 255
                    last_name:
                      type: string
                      description: User's last name
                      maxLength: 255
                    phone_number:
                      type:
                      - string
                      - 'null'
                      pattern: \+\d{4,15}
                      maxLength: 16
                      description: Phone number following the format [E.164](https://www.itu.int/rec/T-REC-E.164/)
                    verification_channel:
                      type: string
                      enum:
                      - email
                      - sms
                      description: Channel selected to send the verification code
                  required:
                  - email
              required:
              - company_name
            example:
              company_name: Shipper Ship Inc.
      responses:
        '201':
          description: Shipper was created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                        description: Unique identifier for this shipper
                        readOnly: true
                      company_name:
                        type: string
                        description: Company name
                        minLength: 10
                        maxLength: 255
                    required:
                    - company_name
              example:
                data:
                  id: 6faebc3d-4423-45eb-bce6-ee6601b155f9
                  company_name: Shipper Ship Inc.
        '422':
          description: Payload is invalid and a shipper can't be created
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                    - invalid_data
                  error_description:
                    type: string
                    description: Description of what happened
                  errors:
                    type: object
                    description: Object where each field is a key and the value is an array of errors
                required:
                - error
                - error_description
              example:
                error: invalid_data
                error_description: Can't create the object
                errors:
                  field_name:
                  - This field is required.
                  other_field:
                  - Expected string but received integer.
      operationId: postApiV2Shippers
      x-operation-id-source: derived
  /api/v2/shippers/{shipper_id}:
    patch:
      summary: Update shipper
      tags:
      - Shippers
      security:
      - Application-JWT:
        - shipper_write
      parameters:
      - in: path
        name: shipper_id
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: Unique identifier for this shipper
                  readOnly: true
                company_name:
                  type: string
                  description: Company name
                  minLength: 10
                  maxLength: 255
              required:
              - company_name
            example:
              company_name: Some Shipper Ship Inc.
      responses:
        '200':
          description: Shipper was updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                        description: Unique identifier for this shipper
                        readOnly: true
                      company_name:
                        type: string
                        description: Company name
                        minLength: 10
                        maxLength: 255
                    required:
                    - company_name
              example:
                data:
                  id: ad5aa25c-3e20-4de8-aeba-3a71d3c3242c
                  company_name: Some Shipper Ship Inc.
        '422':
          description: Payload is invalid and a shipper can't be updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                    - invalid_data
                  error_description:
                    type: string
                    description: Description of what happened
                  errors:
                    type: object
                    description: Object where each field is a key and the value is an array of errors
                required:
                - error
                - error_description
              example:
                error: invalid_data
                error_description: Can't create the object
                errors:
                  field_name:
                  - This field is required.
                  other_field:
                  - Expected string but received integer.
      operationId: patchApiV2ShippersByShipperId
      x-operation-id-source: derived
components:
  securitySchemes:
    Application-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorize the request with the application context (preferred\nfor the endpoints that support it):\n\n```\n{\n  \"sub\": \"sys\",\n  \"iss\": \"token-issuer\",\n  \"exp\": 1626239022,\n  \"iat\": 1517239022\n}\n```\n"
    User-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorize the request with an user context. A payload example\nwould be:\n\n```\n{\n  \"sub\": \"usr:87127882-d1db-4e50-8f7c-c792a80d7c49\",\n  \"iss\": \"token-issuer\",\n  \"iat\": 1517239022,\n  \"exp\": 1626239022\n}\n```\n"
