openapi: 3.2.0
info:
  title: Loadsmart Shipper Accounting Info API
  x-logo:
    altText: Loadsmart API
    url: https://developer.loadsmart.com/logo.svg
  description: Loadsmart API provides endpoints to quote, book and track shipments autonomously.
  version: 1.0.0
servers:
- url: https://api.loadsmart.com
  description: Production server
- url: https://api.sandbox.loadsmart.com
  description: Sandbox environment
tags:
- name: Shipper Accounting Info
paths:
  /api/v2/shippers/{shipper_id}/info:
    post:
      summary: Create shipper billing info
      tags:
      - Shipper Accounting Info
      security:
      - Application-JWT:
        - user_write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                billing_name:
                  type: string
                billing_address:
                  type: string
                billing_city:
                  type: string
                billing_zip_code:
                  type: string
                billing_country:
                  type: string
                billing_state:
                  type: string
                tax_id:
                  type: string
                contact_name:
                  type: string
                contact_email:
                  type: string
                contact_phone:
                  type: string
                terms:
                  type: integer
                notes:
                  type: string
              required:
              - billing_name
              - billing_address
              - billing_city
              - billing_zip_code
              - billing_country
              - billing_state
              - contact_name
              - contact_email
              - contact_phone
              - terms
              - notes
            examples:
              minimal:
                summary: Minimal
                value:
                  billing_name: Trunks Williams
                  billing_address: Color St.
                  billing_city: Pallet Ville
                  billing_state: CA
                  billing_zip_code: 99999
                  billing_country: USA
                  contact_name: John Doe
                  contact_email: John@doe.com
                  contact_phone: null
                  notes: notes
              complete:
                summary: Complete
                value:
                  billing_name: Trunks Williams
                  billing_address: Color St.
                  billing_city: Pallet Ville
                  billing_state: CA
                  billing_zip_code: 99999
                  tax_id: 123-456789
                  billing_country: USA
                  contact_name: John Doe
                  contact_email: John@doe.com
                  contact_phone: null
                  notes: notes
      responses:
        '201':
          description: Accounting Info created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      billing_name:
                        type: string
                      billing_address:
                        type: string
                      billing_city:
                        type: string
                      billing_zip_code:
                        type: string
                      billing_country:
                        type: string
                      billing_state:
                        type: string
                      tax_id:
                        type: string
                      contact_name:
                        type: string
                      contact_email:
                        type: string
                      contact_phone:
                        type: string
                      terms:
                        type: integer
                      notes:
                        type: string
                    required:
                    - billing_name
                    - billing_address
                    - billing_city
                    - billing_zip_code
                    - billing_country
                    - billing_state
                    - contact_name
                    - contact_email
                    - contact_phone
                    - terms
                    - notes
              example:
                data:
                  billing_name: Trunks Williams
                  billing_address: Color St.
                  billing_city: Pallet Ville
                  billing_state: CA
                  billing_zip_code: 99999
                  tax_id: 123-456789
                  billing_country: USA
                  contact_name: John Doe
                  contact_email: John@doe.com
                  contact_phone: null
                  notes: notes
      operationId: postApiV2ShippersByShipperIdInfo
      x-operation-id-source: derived
    get:
      summary: Retrieve Shipper Accounting Info
      tags:
      - Shipper Accounting Info
      security:
      - OAuth:
        - shipper_read
      responses:
        '200':
          description: Retrieve shipper accounting info
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      billing_name:
                        type: string
                      billing_address:
                        type: string
                      billing_city:
                        type: string
                      billing_zip_code:
                        type: string
                      billing_country:
                        type: string
                      billing_state:
                        type: string
                      tax_id:
                        type: string
                      contact_name:
                        type: string
                      contact_email:
                        type: string
                      contact_phone:
                        type: string
                      terms:
                        type: integer
                      notes:
                        type: string
                    required:
                    - billing_name
                    - billing_address
                    - billing_city
                    - billing_zip_code
                    - billing_country
                    - billing_state
                    - contact_name
                    - contact_email
                    - contact_phone
                    - terms
                    - notes
              example:
                data:
                  billing_name: Trunks Williams
                  billing_address: Color St.
                  billing_city: Pallet Ville
                  billing_state: CA
                  billing_zip_code: 99999
                  tax_id: 123-456789
                  billing_country: USA
                  contact_name: John Doe
                  contact_email: John@doe.com
                  contact_phone: null
                  notes: notes
      operationId: getApiV2ShippersByShipperIdInfo
      x-operation-id-source: derived
    put:
      summary: Update shipper billing info
      tags:
      - Shipper Accounting Info
      security:
      - Application-JWT:
        - user_write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                billing_name:
                  type: string
                billing_address:
                  type: string
                billing_city:
                  type: string
                billing_zip_code:
                  type: string
                billing_country:
                  type: string
                billing_state:
                  type: string
                tax_id:
                  type: string
                contact_name:
                  type: string
                contact_email:
                  type: string
                contact_phone:
                  type: string
                terms:
                  type: integer
                notes:
                  type: string
              required:
              - billing_name
              - billing_address
              - billing_city
              - billing_zip_code
              - billing_country
              - billing_state
              - contact_name
              - contact_email
              - contact_phone
              - terms
              - notes
            example:
              billing_name: Trunks Williams
              billing_address: Color St.
              billing_city: Pallet Ville
              billing_state: CA
              billing_zip_code: 99999
              tax_id: 123-456789
              billing_country: USA
              contact_name: John Doe
              contact_email: John@doe.com
              contact_phone: null
              notes: notes
      responses:
        '200':
          description: Accounting Info updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      billing_name:
                        type: string
                      billing_address:
                        type: string
                      billing_city:
                        type: string
                      billing_zip_code:
                        type: string
                      billing_country:
                        type: string
                      billing_state:
                        type: string
                      tax_id:
                        type: string
                      contact_name:
                        type: string
                      contact_email:
                        type: string
                      contact_phone:
                        type: string
                      terms:
                        type: integer
                      notes:
                        type: string
                    required:
                    - billing_name
                    - billing_address
                    - billing_city
                    - billing_zip_code
                    - billing_country
                    - billing_state
                    - contact_name
                    - contact_email
                    - contact_phone
                    - terms
                    - notes
              example:
                data:
                  billing_name: Trunks Williams
                  billing_address: Color St.
                  billing_city: Pallet Ville
                  billing_state: CA
                  billing_zip_code: 99999
                  tax_id: 123-456789
                  billing_country: USA
                  contact_name: John Doe
                  contact_email: John@doe.com
                  contact_phone: null
                  notes: notes
      operationId: putApiV2ShippersByShipperIdInfo
      x-operation-id-source: derived
components:
  securitySchemes:
    Application-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorize the request with the application context (preferred\nfor the endpoints that support it):\n\n```\n{\n  \"sub\": \"sys\",\n  \"iss\": \"token-issuer\",\n  \"exp\": 1626239022,\n  \"iat\": 1517239022\n}\n```\n"
    User-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorize the request with an user context. A payload example\nwould be:\n\n```\n{\n  \"sub\": \"usr:87127882-d1db-4e50-8f7c-c792a80d7c49\",\n  \"iss\": \"token-issuer\",\n  \"iat\": 1517239022,\n  \"exp\": 1626239022\n}\n```\n"
