openapi: 3.2.0
info:
  title: Loadsmart Bids API
  x-logo:
    altText: Loadsmart API
    url: https://developer.loadsmart.com/logo.svg
  description: Loadsmart API provides endpoints to quote, book and track shipments autonomously.
  version: 1.0.0
servers:
- url: https://api.loadsmart.com
  description: Production server
- url: https://api.sandbox.loadsmart.com
  description: Sandbox environment
tags:
- name: Bids
  description: This API allows third parties to create, list, retrieve and accept bids.
paths:
  /api/v2/load-offers/bids:
    get:
      summary: List Bids
      tags:
      - Bids
      security:
      - User-JWT:
        - load_offers_read
      parameters:
      - in: query
        name: status
        schema:
          type: string
          enum:
          - pending
          - awarded
          - accepted
          - timed_out
          - refused
        description: The status of the bid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    description: Number of objects found
                    type: number
                    format: integer
                  next:
                    description: URL for next page of results
                    type: string
                    format: url
                  previous:
                    description: URL for previous page of results
                    type: string
                    format: url
                  results:
                    type: array
                    items:
                      type: object
                      description: The bid properties
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Bid unique identifier (UUID)
                        offer_id:
                          type: string
                          format: uuid
                          description: Offer unique identifier (UUID)
                        price:
                          type: string
                          format: uuid
                          description: Bid price (USD).
                        created_at:
                          type: datetime
                          format: date-time
                          description: Bid creation datetime
                        expires_at:
                          type: datetime
                          format: date-time
                          description: The bid expiration datetime
                        expired_at:
                          type: datetime
                          format: date-time
                          description: The bid datetime that bid was expirated
                        status:
                          type: string
                          enum:
                          - pending
                          - awarded
                          - accepted
                          - timed_out
                          - refused
                          description: Bit status.
              example:
                count: 2
                next: null
                previous: null
                results:
                - id: 3b068fe4-99da-40e5-813a-d0a6de9fd558
                  offer_id: 1471e2b8-bb79-4210-a2d8-5171c4776a54
                  created_at: 2021-05-26 17:12:43.701000+00:00
                  expires_at: null
                  expired_at: null
                  price: 770.1
                  status: pending
                - id: 02df5646-be83-4383-ac76-b2d5557cf927
                  offer_id: 36241edf-545a-496a-a698-ca8fb6c21156
                  created_at: 2021-05-26 17:12:43.688000+00:00
                  expires_at: null
                  expired_at: null
                  price: 61.14
                  status: pending
        '400':
          description: Invalid parameters
        '401':
          description: Not authorized
      operationId: getApiV2LoadOffersBids
      x-operation-id-source: derived
    post:
      summary: Create Bid
      tags:
      - Bids
      security:
      - User-JWT:
        - load_offers_write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Create bid
              properties:
                offer_id:
                  type: string
                  format: uuid
                  description: Offer unique identifier (UUID).
                price:
                  type: string
                  description: Bid Price (USD)
            example:
              offer_id: 47aada86-6ef1-4516-a272-2881397daea9
              price: '809.96'
      responses:
        '201':
          description: Success
          content:
            application/json:
              example:
                id: 7593cbc8-53d0-4e54-87fd-a21f4b6dbb44
                offer_id: 47aada86-6ef1-4516-a272-2881397daea9
                created_at: 2021-05-26 13:43:55.727258+00:00
                expires_at: 2021-05-26 13:58:55.727258+00:00
                expired_at: null
                price: '809.96'
                status: pending
              schema:
                type: object
                description: The bid properties
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Bid unique identifier (UUID)
                  offer_id:
                    type: string
                    format: uuid
                    description: Offer unique identifier (UUID)
                  price:
                    type: string
                    format: uuid
                    description: Bid price (USD).
                  created_at:
                    type: datetime
                    format: date-time
                    description: Bid creation datetime
                  expires_at:
                    type: datetime
                    format: date-time
                    description: The bid expiration datetime
                  expired_at:
                    type: datetime
                    format: date-time
                    description: The bid datetime that bid was expirated
                  status:
                    type: string
                    enum:
                    - pending
                    - awarded
                    - accepted
                    - timed_out
                    - refused
                    description: Bit status.
        '400':
          description: Invalid parameters
        '401':
          description: Not authorized
        '403':
          description: Forbidden
        '404':
          description: Offer doesn't exists or expired
        '410':
          description: Offer is no longer available
        '422':
          description: Could not create the bid with the given data due to one of - ["The carrier is not eligible for this offer", "This offer is unbiddable", "Invalid Price"]
      operationId: postApiV2LoadOffersBids
      x-operation-id-source: derived
  /api/v2/load-offers/bids/{bid_id}:
    get:
      summary: Retrieve Bid
      tags:
      - Bids
      security:
      - User-JWT:
        - load_offers_read
      parameters:
      - in: path
        name: bid_id
        schema:
          description: Bid unique identifier (UUID)
          type: string
          format: uuid
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                description: The bid properties
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Bid unique identifier (UUID)
                  offer_id:
                    type: string
                    format: uuid
                    description: Offer unique identifier (UUID)
                  price:
                    type: string
                    format: uuid
                    description: Bid price (USD).
                  created_at:
                    type: datetime
                    format: date-time
                    description: Bid creation datetime
                  expires_at:
                    type: datetime
                    format: date-time
                    description: The bid expiration datetime
                  expired_at:
                    type: datetime
                    format: date-time
                    description: The bid datetime that bid was expirated
                  status:
                    type: string
                    enum:
                    - pending
                    - awarded
                    - accepted
                    - timed_out
                    - refused
                    description: Bit status.
              example:
                id: 7593cbc8-53d0-4e54-87fd-a21f4b6dbb44
                offer_id: 47aada86-6ef1-4516-a272-2881397daea9
                created_at: 2021-05-26 13:43:55.727258+00:00
                expires_at: 2021-05-26 13:58:55.727258+00:00
                expired_at: null
                price: '809.96'
                status: pending
        '401':
          description: Not authorized
        '403':
          description: Bid is not linked to external outlet
        '404':
          description: Offer doesn't exists
      operationId: getApiV2LoadOffersBidsByBidId
      x-operation-id-source: derived
  /api/v2/load-offers/bids/{bid_id}/accept:
    post:
      summary: Accept Bid
      tags:
      - Bids
      security:
      - User-JWT:
        - load_offers_write
      parameters:
      - in: path
        name: bid_id
        schema:
          description: Bid unique identifier (UUID)
          type: string
          format: uuid
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Load unique identifier (UUID)
              example:
                id: 7593cbc8-53d0-4e54-87fd-a21f4b6dbb44
        '400':
          description: Invalid parameters
        '401':
          description: Not authorized
        '403':
          description: Forbidden
        '404':
          description: Offer doesn't exists
        '409':
          description: Cant accept bid with invalid status
      operationId: postApiV2LoadOffersBidsByBidIdAccept
      x-operation-id-source: derived
components:
  securitySchemes:
    Application-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorize the request with the application context (preferred\nfor the endpoints that support it):\n\n```\n{\n  \"sub\": \"sys\",\n  \"iss\": \"token-issuer\",\n  \"exp\": 1626239022,\n  \"iat\": 1517239022\n}\n```\n"
    User-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorize the request with an user context. A payload example\nwould be:\n\n```\n{\n  \"sub\": \"usr:87127882-d1db-4e50-8f7c-c792a80d7c49\",\n  \"iss\": \"token-issuer\",\n  \"iat\": 1517239022,\n  \"exp\": 1626239022\n}\n```\n"
